services:
  - type: web
    name: smart-temperature-logger
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Remove staticPublishPath since we're serving from the backend
    # staticPublishPath: ./dist
