services:
  - type: web
    name: smart-temperature-logger
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
