services:
  - type: web
    name: smart-temperature-logger
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: smart-temperature-logger
          property: port
    staticPublishPath: ./dist